import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bell, ChevronLeft, Filter, Menu, MoreVertical, Paperclip, PenLine, Search, Send, Settings, Star, Users, X } from 'lucide-react';
import './styles.css';

const demoThreads = [
  { id: 1, person: '9876543210', address: '9876543210@phonemail.local', subject: 'Project update', preview: 'The community centre plan is ready for review.', time: '10:42', unread: true, messages: [{ mine:false, body:'Hello! The community centre plan is ready for review.', subject:'Project update' }, { mine:true, body:'Thanks. I will review it today.' }] },
  { id: 2, person: '9123456789', address: '9123456789@phonemail.local', subject: 'Market meeting', preview: 'Can we meet tomorrow at 10 AM?', time: 'Yesterday', unread: false, messages: [{ mine:false, body:'Can we meet tomorrow at 10 AM?', subject:'Market meeting' }] },
  { id: 3, person: '9000000000', address: '9000000000@phonemail.local', subject: 'Welcome to PhoneMail', preview: 'Your phone-number email identity is ready.', time: 'Mon', unread: false, messages: [{ mine:false, body:'Your phone-number email identity is ready. You can now send and receive emails.', subject:'Welcome to PhoneMail' }] }
];
function App() {
 const [authenticated, setAuthenticated] = useState(false), [phone,setPhone]=useState(''), [otp,setOtp]=useState(''), [step,setStep]=useState('phone');
 const [threads,setThreads]=useState(demoThreads), [selected,setSelected]=useState(null), [compose,setCompose]=useState(false), [search,setSearch]=useState(''), [filter,setFilter]=useState('All'), [menu,setMenu]=useState(false), [notice,setNotice]=useState('');
 const filtered=useMemo(()=>threads.filter(t => (filter!=='Unread'||t.unread) && `${t.person} ${t.subject} ${t.preview}`.toLowerCase().includes(search.toLowerCase())),[threads,filter,search]);
 const requestOtp=()=>{ if(phone.replace(/\D/g,'').length<10) return setNotice('Enter a valid 10-digit phone number.'); setNotice('Demo code sent: 123456'); setStep('otp'); };
 const verify=()=>{if(otp==='123456'){setAuthenticated(true);setNotice('');}else setNotice('Try demo code 123456.');};
 const send=(form)=>{const recipient=form.get('to'), subject=form.get('subject'), body=form.get('body'); if(!recipient||!subject||!body) return setNotice('Please complete To, Subject and Message.'); const item={id:Date.now(),person:recipient.split('@')[0],address:recipient,subject,preview:body,time:'Now',unread:false,messages:[{mine:true,body,subject}]}; setThreads([item,...threads]);setCompose(false);setSelected(item);setNotice('Message sent securely.');};
 if(!authenticated) return <main className="auth"><section className="auth-card"><div className="brand-mark">P</div><p className="eyebrow">ONE IDENTITY · EVERYWHERE</p><h1>Welcome to <span>PhoneMail</span></h1><p className="muted">Your phone number is your simple, secure email identity.</p>{step==='phone'?<><label>Phone number<input autoFocus value={phone} onChange={e=>setPhone(e.target.value)} placeholder="e.g. 9888820532" inputMode="numeric"/></label><button className="primary" onClick={requestOtp}>Continue with OTP <Send size={17}/></button></>:<><button className="back" onClick={()=>setStep('phone')}><ChevronLeft size={18}/> Change phone number</button><label>One-time password<input autoFocus maxLength="6" value={otp} onChange={e=>setOtp(e.target.value)} placeholder="123456" inputMode="numeric"/></label><button className="primary" onClick={verify}>Verify & enter inbox</button></>}<p className="fine">For this local demo, use code <b>123456</b>.</p>{notice&&<p className="notice">{notice}</p>}</section></main>;
 return <div className="shell"><aside className={`sidebar ${menu?'open':''}`}><div className="logo"><div className="logo-dot">P</div>PhoneMail</div><button className="compose" onClick={()=>setCompose(true)}><PenLine size={18}/> Compose</button><nav>{[['Inbox',Users],['Starred',Star],['Drafts',Paperclip],['Settings',Settings]].map(([n,I])=><button key={n} className={n==='Inbox'?'active':''}><I size={18}/>{n}</button>)}</nav><div className="identity"><b>{phone || '9888820532'}</b><small>{phone || '9888820532'}@phonemail.local</small></div></aside><main className="workspace"><header><button className="icon mobile-only" onClick={()=>setMenu(!menu)}><Menu/></button><div className="search"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search phone number or email"/></div><button className="icon"><Bell size={20}/></button><button className="avatar">{(phone||'9').slice(-1)}</button></header><section className="inbox"><div className="inbox-title"><div><p className="eyebrow">YOUR CONVERSATIONS</p><h2>Inbox</h2></div><button className="icon desktop-only"><MoreVertical/></button></div><div className="chips">{['All','Unread','Starred'].map(x=><button key={x} className={filter===x?'chosen':''} onClick={()=>setFilter(x)}>{x==='Unread'&&<Filter size={14}/>} {x}</button>)}</div><div className="thread-list">{filtered.map(t=><button className={`thread ${selected?.id===t.id?'selected':''}`} key={t.id} onClick={()=>{setSelected(t);setThreads(threads.map(x=>x.id===t.id?{...x,unread:false}:x));}}><div className="thread-avatar">{t.person.slice(-2)}</div><div className="thread-copy"><div><b>{t.person}</b><time>{t.time}</time></div><strong>{t.subject}</strong><p>{t.preview}</p></div>{t.unread&&<i/>}</button>)}{!filtered.length&&<p className="empty">No conversations match your search.</p>}</div></section>{selected?<Conversation thread={selected} onBack={()=>setSelected(null)} onReply={body=>{if(!body.trim())return; setThreads(threads.map(t=>t.id===selected.id?{...t,preview:body,messages:[...t.messages,{mine:true,body}]}:t));setSelected({...selected,preview:body,messages:[...selected.messages,{mine:true,body}]});}}/>:<section className="welcome-panel"><div className="brand-mark">P</div><h2>Your email, made human.</h2><p>Select a conversation or compose a new message.</p></section>}</main><button className="fab" onClick={()=>setCompose(true)}><PenLine size={22}/><span>Compose</span></button>{compose&&<Compose close={()=>setCompose(false)} send={send}/>} {notice&&<div className="toast">{notice}<button onClick={()=>setNotice('')}><X size={16}/></button></div>}</div>
}
function Conversation({thread,onBack,onReply}){const [reply,setReply]=useState('');return <section className="conversation"><header className="conversation-head"><button className="icon" onClick={onBack}><ChevronLeft/></button><div className="thread-avatar">{thread.person.slice(-2)}</div><div><b>{thread.person}</b><small>{thread.address}</small></div><button className="icon more"><MoreVertical/></button></header><div className="message-area"><div className="subject">Subject: {thread.subject}</div>{thread.messages.map((m,i)=><div key={i} className={`bubble ${m.mine?'mine':''}`}>{m.body}</div>)}</div><form className="reply" onSubmit={e=>{e.preventDefault();onReply(reply);setReply('')}}><input value={reply} onChange={e=>setReply(e.target.value)} placeholder="Write a reply…"/><button aria-label="Send reply"><Send size={19}/></button></form></section>}
function Compose({close,send}){return <div className="modal-bg"><form className="compose-card" action={send}><div className="compose-head"><b>New message</b><button type="button" className="icon" onClick={close}><X/></button></div><input name="to" placeholder="To (phone-number@phonemail.local)"/><div className="cc-row"><input name="cc" placeholder="CC"/><input name="bcc" placeholder="BCC"/></div><input name="subject" placeholder="Subject"/><textarea name="body" placeholder="Write your message…"/><div className="compose-actions"><button type="button" className="icon"><Paperclip/></button><button className="primary">Send <Send size={16}/></button></div></form></div>}
createRoot(document.getElementById('root')).render(<App/>);
